FROM python:3.12.4-slim

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY create_index.py create_index.py
COPY documents.json documents.json


ENTRYPOINT ["sleep", "6000"]